name: Action runs everyday
on:
  schedule:
    - cron: '10 22 * * *' #runs everyday at certain hour and minute 
  workflow_dispatch:  # 🔹 This allows manual execution, I have used this only to test without waiting until automation trigger time

jobs:
  commit: #Since commit is the action in this workflow
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v4
    
    - name: Making a change in order to avoid empty commit
      run: |
        echo "Automated commit on $(date)" >> daily_commit_iitm_raji.log  # Appends to the log file
        
    - name: Add commit (by 23ds3000149@ds.study.iitm.ac.in)
      run: |
        echo "This commit runs everyday at certain time and automated through Workflows in Github!"
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "23ds3000149@ds.study.iitm.ac.in"
        git add .
        git commit -m "Automated daily commit - $(date)"
        git push

