name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '50 21 * * 6'
  workflow_dispatch:  # 🔹 This allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"
